# Generated by Django 4.0.3 on 2022-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_image', models.ImageField(upload_to='image/%Y/%m/%d/')),
                ('author', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(max_length=4)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(max_length=10)),
                ('comments', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
