# Generated by Django 4.0.3 on 2022-04-10 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_rating_alter_books_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['time_create', 'book_title'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=255, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='comments',
            field=models.TextField(verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='books',
            name='release_year',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1900)], verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='books',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
