# Generated by Django 4.0.3 on 2022-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='info_author',
            field=models.CharField(max_length=255, null=True, verbose_name='Контакты владельца'),
        ),
    ]
