# Generated by Django 4.0.3 on 2022-04-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_info_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
