# Generated by Django 4.0.3 on 2022-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=255, verbose_name='Повторение пароля')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Электронная почта')),
                ('user_photo', models.ImageField(upload_to='avatar/%Y/%m/%d/', verbose_name='Фото пользователя')),
                ('area_of_residence', models.CharField(max_length=50, verbose_name='Район проживания')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['registration_date', 'username'],
            },
        ),
    ]
